### ISSUE TITLE
propagate: support functions with multiple independent arguments

### ISSUE THREAD

**Issue by HDembinski** [HDembinski/jacobi#15]
Often, one has a function that takes independent arguments. Propagating this currently is a bit cumbersome, one has to combine the arguments into a vector and the covariances into joint block covariance matrix. `propagate` could be made more flexible to make this easier. I am not sure how the signature should look like, though.

```py
def func(a, b):
     ....

a = [...]
b = [...]
cov_a = [...]
cov_b = [...]

# option 1
propagate(func, a, b, cov_a, cov_b)

# option 2
propagate(func, a, cov_a, b, cov_b)

# option 3
propagate(func, (a, cov_a), (b, cov_b))
```

Options 1 and 2 are natural extensions of the current calling convention, just the order of values and covariances differ. I am not sure what is most natural. I am leaning towards option 2.

Option 3 requires more typing and is not really much safer.

**Comment by jpivarski** [comment]
A fourth option would be to make everything beyond `func` a keyword-only argument, though that necessitates more typing:

```python
# option 4
propagate(func, a=a, cov_a=cov_a, b=b, cov_b=cov_b)
```

When _calling_ such a function, I would tend toward calling it with keywords to be insensitive to changes in the calling convention (shouldn't happen in a backward-compatible library, but hey, I can be more defensive than I need to be) and also because I don't have to look up the correct order in the documentation.

If `a`/`b` and `cov_a`/`cov_b` have different data types, checked statically by mypy and/or checked at runtime in the `propagate` function, then option 2 would provide the quickest feedback when it's used incorrectly (as quick as option 4, that is). The type-check would complain if `b` is supplied where `cov_a` is expected. Quick feedback when it's used improperly may be the most important thing.

Independent of that, is it possible that the set {`a`, `b`} might grow to include a `c` in the future? If so, then option 2 best supports this growth in a backward-compatible way. Is it possible that the set {_x_, `cov_`_x_} might grow to include—I don't know—`bias_`_x_ or `mean_`_x_ in the future? If so, then option 1 best supports this growth. Option 4 supports both kinds of growth.

**Comment by HDembinski** [comment]
> A fourth option would be to make everything beyond `func` a keyword-only argument, though that necessitates more typing:

I first thought that this is a great suggestion, but I think one should use the highly dynamical features of Python sparingly. To implement this, I need to turn the signature into `def propagate(func, *args, **kwargs)` and `inspect` the function to figure out its parameters. The function may not have a signature to inspect.

**Comment by HDembinski** [comment]
> When _calling_ such a function, I would tend toward calling it with keywords to be insensitive to changes in the calling convention (shouldn't happen in a backward-compatible library, but hey, I can be more defensive than I need to be) and also because I don't have to look up the correct order in the documentation.

I disagree. People should never change the order of function arguments, but the names of keywords can change. I avoid calling arguments by name.

Also please keep in mind that users will apply this to small functions they have written themselves, the functions are not coming from a third-party library.

**Comment by HDembinski** [comment]
> If a/b and cov_a/cov_b have different data types, checked statically by mypy and/or checked at runtime in the propagate function, then option 2 would provide the quickest feedback when it's used incorrectly (as quick as option 4, that is). The type-check would complain if b is supplied where cov_a is expected. Quick feedback when it's used improperly may be the most important thing.

The arguments are all `ArrayLike`, so mypy unfortunately won't be able to help here. a,b are always 1D, and cov_a, cov_b are usually 2D. I think mypy cannot check that (?). I will check it at runtime, but I won't be able to catch all possible mistakes, since the API allows passing an 1D array for cov_a, which is then interpreted as "errors" and the covariance is internally computed as np.diag(cov_a ** 2). In that case, a,b,cov_a,cov_b are all 1D arrays and there is no way to tell that the user passed the arguments in the correct order.

> Independent of that, is it possible that the set {a, b} might grow to include a c in the future? If so, then option 2 best supports this growth in a backward-compatible way. Is it possible that the set {x, cov_x} might grow to include—I don't know—bias_x or mean_x in the future? If so, then option 1 best supports this growth. Option 4 supports both kinds of growth.

Yes, I think that's the killer argument for option 2! I had a gut feeling like this, but it was not clear in my mind. Thank you!

**Comment by eduardo-rodrigues** [comment]
Hi @HDembinski, coming in a bit late. I would also decide thinking of a possible step further with a `c` argument, as mentioned above. To avoid having too complicated a signature with a keyword argument, which is not great here, I think I vote for option 2 as well for the pretty comprehensive pros and cons raised already.
